name=JSONParser
version=0.9.0
author=Romain Brestac
maintainer=Romain Brestac
sentence=JSON parser & printer for ESP.
paragraph=Parse with zero-copy and print updated values.
category=Utility
url=https://github.com/brestac/JSONParser
architectures=esp8266